disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - sorted_first_last
  - vertical_parameter_alignment_on_call
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 100
  excluded:
    - id
    - url
    - URL
    - db
    - UI
    - API
    - iOS
    - app
    - 'x'
    - 'y'

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    message: "Use proper logging instead of print statements"
    severity: warning
  
  no_force_cast:
    name: "No Force Cast"
    regex: "as!"
    message: "Use safe casting with 'as?' instead of force casting"
    severity: error
  
  no_force_unwrapping:
    name: "No Force Unwrapping"
    regex: "![^=]"
    message: "Use safe unwrapping instead of force unwrapping"
    severity: warning

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import

excluded:
  - .build
  - .swiftpm
  - Package.swift
  - Tests/LensDataBaseTests/LinuxMain.swift

# Reporter
reporter: "xcode"

# Warnings as errors
strict: false