disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - force_cast
  - force_unwrapping
  - nesting
  - type_body_length
  - function_body_length

opt_in_rules:
  - empty_count
  - explicit_init
  - sorted_imports

excluded:
  - Carthage
  - Pods
  - fastlane
  - .build

reporter: xcode
