name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install swiftlint
          gem install xcpretty

      - name: Run SwiftLint
        run: swiftlint lint --strict

      - name: Build project
        run: |
          set -o pipefail
          xcodebuild -scheme LensDataBase \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
            clean build | xcpretty
